# Generated by Django 4.1.2 on 2022-10-27 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'verbose_name': 'Follower', 'verbose_name_plural': 'Followers'},
        ),
    ]
