# Generated by Django 4.1 on 2022-09-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0003_post_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='published_cond',
        ),
    ]
