# Generated by Django 4.1.2 on 2022-10-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0002_alter_wish_wish_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='announce',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
